"""
Field mapping config: ERPNext DocType -> reporting DB table.
Each entry drives the generic sync logic in sync_service.py.

Tables using ERPNext's own `name` as the reporting primary key match
directly on pk_reporting. Child-table entities (no natural business PK)
instead track ERPNext's row identity in erpnext_name and match on that
via match_field, so re-syncing never creates duplicates.
"""
import models

SYNC_CONFIG = [
    # ---------- Tier 1: no dependencies ----------
    {
        "doctype": "Customer",
        "model": models.Customer,
        "pk_erpnext": "name",
        "pk_reporting": "customer_id",
        "field_map": {
            "name": "customer_id",
            "customer_name": "customer_name",
            "customer_group": "customer_group",
            "territory": "territory",
            "account_manager": "account_manager_user",
            "mobile_no": "phone",
            "email_id": "email",
            "disabled": "is_disabled",
            "custom_company_activity": "company_activity",
            "custom_number_of_employees": "employee_count_band",
            "custom_country": "country",
            "custom_number_of_devices": "device_count",
            "custom_number_of_devices_installation_per_month": "install_volume_monthly",
            "custom_total_monthly_devices": "total_monthly_devices",
            "custom_total_monthly_devices_sum_usd": "total_monthly_devices_usd",
            "custom_how_many_gps": "gps_installs_monthly",
            "custom_number_of_technicians": "technician_count_general",
            "custom_how_many_technicians": "gps_technician_count",
            "custom_client_progress": "client_progress",
            "custom_target_market": "target_market",
            "custom_is_assigned": "is_assigned",
            "custom_date_of_assignment": "assigned_on",
            "creation": "created_at",
            "modified": "updated_at",
        },
    },
    {
        "doctype": "Leads",  # note: BoxTech's custom DocType, not standard "Lead"
        "model": models.Lead,
        "pk_erpnext": "name",
        "pk_reporting": "lead_id",
        "field_map": {
            "name": "lead_id",
            "client_name": "client_name",
            "country": "country",
            "lead_date": "lead_date",
            "lead_owner": "owner_user",
            "expected_closing_date": "expected_closing_date",
            "probability": "probability",
            "sales_status": "status",
            "stage_comments": "stage_comments",
            "manufacturer": "manufacturer",
            "category": "category",
            "client_requirement_and_pain_point": "client_requirement_notes",
            "solution": "solution",
            "quantity": "quantity",
            "total": "total_value",
            "base_total": "base_total_value",
            "creation": "created_at",
            "modified": "updated_at",
        },
    },
    {
        "doctype": "Task",
        "model": models.Task,
        "pk_erpnext": "name",
        "pk_reporting": "task_id",
        "field_map": {
            "name": "task_id",
            "subject": "subject",
            "status": "status",
            "priority": "priority",
            "exp_start_date": "expected_start",
            "exp_end_date": "expected_end",
            "completed_by": "completed_by_user",
            "completed_on": "completed_on",
            "creation": "created_at",
            "modified": "updated_at",
        },
    },
    {
        "doctype": "ToDo",
        "model": models.Todo,
        "pk_erpnext": "name",
        "pk_reporting": "todo_id",
        "field_map": {
            "name": "todo_id",
            "description": "description",
            "status": "status",
            "priority": "priority",
            "date": "due_date",
            "allocated_to": "assigned_to_user",
            "reference_type": "linked_doctype",
            "reference_name": "linked_record_id",
            "creation": "created_at",
            "modified": "updated_at",
        },
    },
    {
        "doctype": "Communication",
        "model": models.Communication,
        "pk_erpnext": "name",
        "pk_reporting": "communication_id",
        "field_map": {
            "name": "communication_id",
            "communication_medium": "medium",
            "sender": "sender",
            "recipients": "recipients",
            "communication_date": "communication_at",
            "sent_or_received": "direction",
            "status": "status",
            "reference_doctype": "linked_doctype",
            "reference_name": "linked_record_id",
            "subject": "subject",
            "creation": "created_at",
            "modified": "updated_at",
        },
    },
    {
        "doctype": "Call Log",
        "model": models.CallLog,
        "pk_erpnext": "name",
        "pk_reporting": "call_id",
        "field_map": {
            "name": "call_id",
            "from": "from_number",
            "to": "to_number",
            "employee_user_id": "handled_by_user",
            "medium": "call_medium",
            "start_time": "call_start",
            "end_time": "call_end",
            "duration": "duration_seconds",
            "type": "call_direction",
            "type_of_call": "call_type",
            "status": "call_status",
            "customer": "customer_id",
            "creation": "created_at",
            "modified": "updated_at",
            # NOTE: recording_url and summary intentionally excluded — standing
            # privacy decision, see AI Model / Query Safety document.
        },
    },

    # ---------- Tier 1b: HR module (Department -> Employee -> Attendance/
    # Checkin). Awaiting read access grant from Hassan for these four
    # doctypes -- will insert 0 rows and log permission errors until then,
    # which is expected and harmless (see run_sync's per-doctype error
    # handling; a failure here doesn't block any other table's sync). ----
    {
        "doctype": "Department",
        "model": models.Department,
        "pk_erpnext": "name",
        "pk_reporting": "department_name",
        "field_map": {
            # ERPNext's "name" is the real doc ID (e.g. "Software Department  - BT")
            # -- this is what Employee.department actually stores as its link
            # value, confirmed 2026-07-18. "department_name" is just the
            # pretty display label (e.g. "Software Department") and does NOT
            # match Employee.department, despite the similar field name --
            # syncing it as our join key (as an earlier version of this
            # config did) made joining Employee to Department silently
            # impossible.
            "name": "department_name",
            "department_name": "department_label",
            "parent_department": "parent_department",
            "company": "company",
        },
    },
    {
        "doctype": "Employee",
        "model": models.Employee,
        "pk_erpnext": "name",
        "pk_reporting": "employee_id",
        "field_map": {
            "name": "employee_id",
            "employee_name": "employee_name",
            "user_id": "user_id",
            "department": "department",
            # ERPNext's own system field, present on every doctype -- the
            # record's real historical creation timestamp. Lets us answer
            # "have new employees been added" directly instead of
            # inferring it from activity/login data.
            "creation": "created_at",
        },
    },
    {
        "doctype": "Attendance",
        "model": models.Attendance,
        "pk_erpnext": "name",
        "pk_reporting": "attendance_id",
        "field_map": {
            "name": "attendance_id",
            "employee": "employee_id",
            "employee_name": "employee_name",
            "attendance_date": "attendance_date",
            "status": "status",
            "working_hours": "working_hours",
            "in_time": "in_time",
            "out_time": "out_time",
            "department": "department",
        },
    },
    {
        "doctype": "Employee Checkin",
        "model": models.EmployeeCheckin,
        "pk_erpnext": "name",
        "pk_reporting": "checkin_id",
        "field_map": {
            "name": "checkin_id",
            "employee": "employee_id",
            "log_type": "log_type",
            "time": "time",
            "shift_start": "shift_start",
            "shift_end": "shift_end",
        },
    },

    # ---------- Tier 2: depend on Customer ----------
    {
        "doctype": "Opportunity",
        "model": models.Opportunity,
        "pk_erpnext": "name",
        "pk_reporting": "opportunity_id",
        "field_map": {
            "name": "opportunity_id",
            "party_name": "customer_id",
            "opportunity_from": "opportunity_from",
            "customer_name": "customer_name",
            "status": "status",
            "opportunity_owner": "owner_user",
            "opportunity_amount": "opportunity_amount",
            "expected_closing": "expected_closing_date",
            "transaction_date": "opportunity_date",
            "order_lost_reason": "lost_reason",
            "custom_opportunity_date": "opportunity_custom_date",
            "custom_opportunity_stages": "pipeline_stage",
            "custom_stage_comments_": "stage_comments",
            "custom_manufacturer": "device_manufacturer",
            "custom_category": "product_category",
            "custom_technical_requirements": "client_requirement_notes",
            "custom_opportunity_details": "proposed_solution",
            "custom_quantity": "device_qty",
            "custom_model": "device_model",
            "custom_unit_price_usd": "unit_price_usd",
            "custom_total_sum_usd": "total_value_usd",
            "creation": "created_at",
            "modified": "updated_at",
        },
    },
    {
        "doctype": "Sales Order",
        "model": models.SalesOrder,
        "pk_erpnext": "name",
        "pk_reporting": "sales_order_id",
        "field_map": {
            "name": "sales_order_id",
            "customer": "customer_id",
            "customer_name": "customer_name",
            "transaction_date": "order_date",
            "delivery_date": "delivery_date",
            "status": "status",
            "delivery_status": "delivery_status",
            "billing_status": "billing_status",
            "grand_total": "order_value",
            "currency": "currency",
            "creation": "created_at",
            "modified": "updated_at",
        },
    },
    {
        "doctype": "Sales Invoice",
        "model": models.SalesInvoice,
        "pk_erpnext": "name",
        "pk_reporting": "invoice_id",
        "field_map": {
            "name": "invoice_id",
            "customer": "customer_id",
            "customer_name": "customer_name",
            "posting_date": "invoice_date",
            "due_date": "due_date",
            "status": "status",
            "grand_total": "invoice_value",
            "outstanding_amount": "outstanding_amount",
            "is_return": "is_credit_note",
            "creation": "created_at",
            "modified": "updated_at",
        },
    },
    {
        "doctype": "Logistics Entry",
        "model": models.LogisticsEntry,
        "pk_erpnext": "name",
        "pk_reporting": "logistics_entry_id",
        "field_map": {
            "name": "logistics_entry_id",
            "status": "sales_status",
            "date": "entry_date",
            "order_no": "related_order_id",
            "customer": "customer_id",
            "shipment_status": "shipment_status",
            "qty": "device_qty",
            "total": "shipment_value",
            "courier": "courier",
            "shipment_no": "shipment_no",
            "destination": "destination",
            "duty_paid_by": "duty_paid_by",
            "delivery_status": "delivery_status",
            "payment_status": "payment_status",
            "payment_date": "payment_date",
            "imei_count": "imei_count",
            "creation": "created_at",
            "modified": "updated_at",
        },
    },

    # ---------- Tier 3: depends on Opportunity ----------
    {
        "doctype": "Quotation",
        "model": models.Quotation,
        "pk_erpnext": "name",
        "pk_reporting": "quotation_id",
        "field_map": {
            "name": "quotation_id",
            "customer_name": "customer_name",
            "quotation_to": "quotation_to",
            "transaction_date": "transaction_date",
            "status": "status",
            "grand_total": "grand_total",
            "opportunity": "opportunity_id",
            "creation": "created_at",
            "modified": "updated_at",
        },
    },

    # ---------- Tier 4: child tables (require migration_005 first) ----------
    {
        "doctype": "Customer Activity Detail",
        "model": models.CustomerActivityDetail,
        "pk_erpnext": "name",
        "pk_reporting": "id",
        "match_field": "erpnext_name",
        "parent_doctype": "Customer",
        "field_map": {
            "name": "erpnext_name",
            "parent": "customer_id",
            "owner": "logged_by_user",
            "date": "activity_date",
            "time": "activity_time",
            "point_of_contact": "point_of_contact_role",
            "activity_type": "activity_type",
            "phone_call_scenario": "activity_scenario",
            "result": "result",
            "progress": "status",
            "phone_call_scenario_other": "scenario_other_detail",
        },
    },
    {
        "doctype": "Customer Contacts",
        "model": models.CustomerContact,
        "pk_erpnext": "name",
        "pk_reporting": "id",
        "match_field": "erpnext_name",
        "parent_doctype": "Customer",
        "field_map": {
            "name": "erpnext_name",
            "parent": "customer_id",
            "role": "contact_role",
            "name1": "contact_name",
            "email": "contact_email",
            "phone_number": "contact_phone",
        },
    },
    {
        "doctype": "Customer Monthly Devices",
        "model": models.CustomerMonthlyDevice,
        "pk_erpnext": "name",
        "pk_reporting": "id",
        "match_field": "erpnext_name",
        "parent_doctype": "Customer",
        "field_map": {
            "name": "erpnext_name",
            "parent": "customer_id",
            "manufacturer": "manufacturer",
            "model": "model",
            "qty_per_month": "monthly_qty",
            "price_usd": "unit_price_usd",
            "sum_usd": "monthly_value_usd",
        },
    },
    {
        "doctype": "Customer Project Task",
        "model": models.CustomerProjectTask,
        "pk_erpnext": "name",
        "pk_reporting": "id",
        "match_field": "erpnext_name",
        "parent_doctype": "Customer",
        "field_map": {
            "name": "erpnext_name",
            "parent": "customer_id",
            "project_name": "project_name",
            "device_model": "device_model",
            "project_stage": "project_stage",
            "reason": "reason",
            "use_case": "use_case",
            "quantity": "quantity",
            "price_in_usd": "unit_price_usd",
            "project_value": "project_value_usd",
        },
    },
    {
        "doctype": "Sample Testing Stages",
        "model": models.CustomerSampleTesting,
        "pk_erpnext": "name",
        "pk_reporting": "id",
        "match_field": "erpnext_name",
        "parent_doctype": "Customer",
        "field_map": {
            "name": "erpnext_name",
            "parent": "customer_id",
            "date": "test_date",
            "stage": "test_stage",
            "details": "notes",
        },
    },
    {
        "doctype": "Logistics Entry Item",
        "model": models.LogisticsEntryItem,
        "pk_erpnext": "name",
        "pk_reporting": "id",
        "match_field": "erpnext_name",
        "parent_doctype": "Logistics Entry",
        "field_map": {
            "name": "erpnext_name",
            "parent": "logistics_entry_id",
            "model": "item_model",
            "manufacturer": "manufacturer",
            "quantity": "quantity",
            "price": "unit_price",
            "amount": "line_amount",
        },
    },
    {
        "doctype": "Logistics Comments",
        "model": models.LogisticsComment,
        "pk_erpnext": "name",
        "pk_reporting": "id",
        "match_field": "erpnext_name",
        "parent_doctype": "Logistics Entry",
        "field_map": {
            "name": "erpnext_name",
            "parent": "logistics_entry_id",
            "date_time": "comment_at",
            "team": "team",
            "comment_by": "commented_by_user",
            "comment": "comment_text",
        },
    },
    {
        "doctype": "IMEI Detail",
        "model": models.ImeiDetail,
        "pk_erpnext": "name",
        "pk_reporting": "id",
        "match_field": "erpnext_name",
        "parent_doctype": "Logistics Entry",
        "field_map": {
            "name": "erpnext_name",
            "parent": "logistics_entry_id",
            "customer": "customer_id",
            "item": "item_id",
            "imei_number": "imei_number",
            "serial_number": "serial_number",
        },
    },
]
